service: task-manager-backend
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  deploymentBucket:
    name: task-manager-backend-deploy-bucket
  httpApi:
    cors:
      allowedOrigins:
        - 'http://localhost:5173'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: true
  environment:
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  registerUser:
    handler: auth_handlers.registerUser
    events:
      - httpApi:
          path: /register
          method: post
  loginUser:
    handler: auth_handlers.loginUser
    events:
      - httpApi:
          path: /login
          method: post
  createTask:
    handler: handler.createTask
    events:
      - httpApi:
          path: /tasks
          method: post
  getTasks:
    handler: handler.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
  updateTaskStatus:
    handler: handler.updateTaskStatus
    events:
      - httpApi:
          path: /tasks/{taskId}/status
          method: put
  deleteTask:
    handler: handler.deleteTask
    events:
      - httpApi:
          path: /tasks/{taskId}
          method: delete

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements

custom:
  dotenv:
    include:
      - MONGO_URI
      - JWT_SECRET
  pythonRequirements:
    dockerizePip: true
    invalidateCaches: true