openapi: 3.1.0
info:
  title: Task Manager API
  version: 1.0.0
  description: |
    API para el registro de usuarios, autenticaci칩n y gesti칩n de tareas.
servers:
  - url: https://{your-api-id}.execute-api.us-east-1.amazonaws.com/dev
    description: Entorno de desarrollo (stage `dev`)
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    AuthResponse:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    Task:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
      required:
        - id
        - title
        - completed
    CreateTaskRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
      required:
        - title
    UpdateStatusRequest:
      type: object
      properties:
        completed:
          type: boolean
      required:
        - completed
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
paths:
  /register:
    post:
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Usuario registrado correctamente
        '400':
          description: Error en los datos de entrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /login:
    post:
      summary: Autenticar usuario y obtener token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Autenticaci칩n exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Credenciales inv치lidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /tasks:
    post:
      summary: Crear una nueva tarea
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Tarea creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: No autorizado
    get:
      summary: Obtener todas las tareas del usuario autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: No autorizado
  /tasks/{taskId}/status:
    put:
      summary: Actualizar estado de una tarea
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: taskId
          schema:
            type: string
          required: true
          description: ID de la tarea
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusRequest'
      responses:
        '200':
          description: Tarea actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: No autorizado
        '404':
          description: Tarea no encontrada
  /tasks/{taskId}:
    delete:
      summary: Eliminar una tarea
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: taskId
          schema:
            type: string
          required: true
          description: ID de la tarea
      responses:
        '204':
          description: Tarea eliminada correctamente
        '401':
          description: No autorizado
        '404':
          description: Tarea no encontrada
security:
  - bearerAuth: []
